In [48]:
import pandas as pd
import cupy as cp
import cudf
import cuml
import torch
import gc

In [49]:
df = cudf.read_csv('heart_disease_health_indicators_BRFSS2015.csv')
df

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,45.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,5.0,0.0,1.0,5.0,6.0,7.0
253676,0.0,1.0,1.0,1.0,18.0,0.0,0.0,2.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
253677,0.0,0.0,0.0,1.0,28.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,5.0,2.0
253678,0.0,1.0,0.0,1.0,23.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,7.0,5.0,1.0
253679,1.0,1.0,1.0,1.0,25.0,0.0,0.0,2.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

In [50]:
from cuml.preprocessing import MaxAbsScaler
from cuml.preprocessing import MinMaxScaler
from cuml.preprocessing import Normalizer
from cuml.preprocessing import RobustScaler
from cuml.preprocessing import StandardScaler
from cuml.preprocessing import Binarizer
from cuml.preprocessing import FunctionTransformer
from cuml.preprocessing import KBinsDiscretizer
import time

In [51]:
class Normalization(object):
    def __init__(self, dataset):
        self.dataset = dataset.copy().reset_index(drop = True)
        self.dataset_numpy_array = self.dataset.copy().to_numpy()
        self.X = cp.array(self.dataset_numpy_array)


    def MaxAbsScaler(self):
        global maxAbsScaler_global

        transformer = MaxAbsScaler().fit(self.X)
        df_maxAbs_scaler_transform = transformer.transform(self.X)
        
        maxAbsScaler_global = cudf.DataFrame(df_maxAbs_scaler_transform, columns = ['HeartDiseaseorAttack', 'HighBP', 'HighChol', 'CholCheck', 
                                                                                    'BMI','Smoker', 'Stroke', 'Diabetes', 'PhysActivity', 'Fruits', 
                                                                                    'Veggies', 'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 
                                                                                    'GenHlth','MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 
                                                                                    'Age', 'Education','Income'])
    
    def MinMaxScaler(self):
        global MinMaxScaler_global

        transformer = MinMaxScaler().fit(self.X)
        df_MinMaxScaler_transform = transformer.transform(self.X)

        MinMaxScaler_global = cudf.DataFrame(df_MinMaxScaler_transform, columns = ['HeartDiseaseorAttack', 'HighBP', 'HighChol', 'CholCheck', 
                                                                                    'BMI','Smoker', 'Stroke', 'Diabetes', 'PhysActivity', 'Fruits', 
                                                                                    'Veggies', 'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 
                                                                                    'GenHlth','MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 
                                                                                    'Age', 'Education','Income'])

    def Normalizer(self):
        global normalizer_global

        transformer = Normalizer().fit(self.X)
        df_normalizer_transform = transformer.transform(self.X)

        normalizer_global = cudf.DataFrame(df_normalizer_transform, columns = ['HeartDiseaseorAttack', 'HighBP', 'HighChol', 'CholCheck', 
                                                                                    'BMI','Smoker', 'Stroke', 'Diabetes', 'PhysActivity', 'Fruits', 
                                                                                    'Veggies', 'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 
                                                                                    'GenHlth','MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 
                                                                                    'Age', 'Education','Income'])

    def RobustScaler(self):
        global robust_scaler_global

        transformer = RobustScaler().fit(self.X)
        df_robust_scaler_transform = transformer.transform(self.X)

        robust_scaler_global = cudf.DataFrame(df_robust_scaler_transform, columns = ['HeartDiseaseorAttack', 'HighBP', 'HighChol', 'CholCheck', 
                                                                                    'BMI','Smoker', 'Stroke', 'Diabetes', 'PhysActivity', 'Fruits', 
                                                                                    'Veggies', 'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 
                                                                                    'GenHlth','MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 
                                                                                    'Age', 'Education','Income'])

    def StandardScaler(self):
        global standard_scaler_global

        transformer = StandardScaler().fit(self.X)
        df_standard_scaler_transform = transformer.transform(self.X)

        standard_scaler_global = cudf.DataFrame(df_standard_scaler_transform, columns = ['HeartDiseaseorAttack', 'HighBP', 'HighChol', 'CholCheck', 
                                                                                    'BMI','Smoker', 'Stroke', 'Diabetes', 'PhysActivity', 'Fruits', 
                                                                                    'Veggies', 'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 
                                                                                    'GenHlth','MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 
                                                                                    'Age', 'Education','Income'])

    def Binarizer(self):
        global binarizer_global

        transformer = Binarizer().fit(self.X)
        df_binarizer_transform = transformer.transform(self.X)

        binarizer_global = cudf.DataFrame(df_binarizer_transform, columns = ['HeartDiseaseorAttack', 'HighBP', 'HighChol', 'CholCheck', 
                                                                                    'BMI','Smoker', 'Stroke', 'Diabetes', 'PhysActivity', 'Fruits', 
                                                                                    'Veggies', 'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 
                                                                                    'GenHlth','MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 
                                                                                    'Age', 'Education','Income'])

    def FunctionTransformer(self):
        global function_transformer_global

        transformer = FunctionTransformer(func=cp.log1p)
        df_function_transformer_transform = transformer.transform(self.X)

        function_transformer_global = cudf.DataFrame(df_function_transformer_transform, columns = ['HeartDiseaseorAttack', 'HighBP', 'HighChol', 'CholCheck', 
                                                                                    'BMI','Smoker', 'Stroke', 'Diabetes', 'PhysActivity', 'Fruits', 
                                                                                    'Veggies', 'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 
                                                                                    'GenHlth','MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 
                                                                                    'Age', 'Education','Income'])

    def KBinsDiscretizer(self):
        global KBinsDiscretizer_global

        transformer = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='uniform').fit(self.X)
        df_KBinsDiscretizer_transform = transformer.transform(self.X)

        KBinsDiscretizer_global = cudf.DataFrame(df_KBinsDiscretizer_transform, columns = ['HeartDiseaseorAttack', 'HighBP', 'HighChol', 'CholCheck', 
                                                                                    'BMI','Smoker', 'Stroke', 'Diabetes', 'PhysActivity', 'Fruits', 
                                                                                    'Veggies', 'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 
                                                                                    'GenHlth','MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 
                                                                                    'Age', 'Education','Income'])


    def main(self):
        st = time.time()
        self.MaxAbsScaler()
        self.MinMaxScaler()
        self.Normalizer()
        self.RobustScaler()
        self.StandardScaler()
        self.Binarizer()
        self.FunctionTransformer()
        self.KBinsDiscretizer()

        et = time.time()
        elapsed_time = et - st
        print('Execution time:', elapsed_time, 'seconds')

In [52]:
norm = Normalization(df)

In [53]:
norm.main()

Execution time: 0.3791921138763428 seconds

In [54]:
class Data_Generation(object):

    def __init__(self, dataset, size, data_type):
        self.dataset = dataset.copy().reset_index(drop = True)
        self.size = size
        self.data_type = data_type
        self.HighBP_nums = []
        self.HighChol_nums = []
        self.CholCheck_nums = []
        self.Smoker_nums = []
        self.Stroke_nums = []
        self.PhysActivity_nums = []
        self.Fruits_nums = []
        self.Veggies_nums= []
        self.HvyAlcoholConsump_nums = []
        self.AnyHealthcare_nums = []
        self.NoDocbcCost_nums = []
        self.DiffWalk_nums = []
        self.Sex_nums = []
        self.BMI_nums = []
        self.Diabetes_nums = []
        self.GenHlth_nums = []
        self.MentHlth_nums = []
        self.PhysHlth_nums = []
        self.Age_nums = []
        self.Education_nums = []
        self.Income_nums = []
        self.generated_data = []

    def generating_data(self):
        self.HighBP_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.HighChol_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.CholCheck_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.Smoker_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.Stroke_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.PhysActivity_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.Fruits_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.Veggies_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.HvyAlcoholConsump_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.AnyHealthcare_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.NoDocbcCost_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.DiffWalk_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.Sex_nums = cp.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.BMI_nums = cp.random.choice(range(12, 99), size=self.size).astype(self.data_type)
        self.Diabetes_nums = cp.random.choice(range(0, 3), size = self.size).astype(self.data_type)
        self.GenHlth_nums = cp.random.choice(range(1, 6), size = self.size).astype(self.data_type)
        self.MentHlth_nums = cp.random.choice(range(0, 31), size = self.size).astype(self.data_type)
        self.PhysHlth_nums = cp.random.choice(range(0, 31), size = self.size).astype(self.data_type)
        self.Age_nums = cp.random.choice(range(1, 14), size = self.size).astype(self.data_type)
        self.Education_nums = cp.random.choice(range(1, 7), size = self.size).astype(self.data_type)
        self.Income_nums = cp.random.choice(range(1, 9), size = self.size).astype(self.data_type)
        
        
    def generating_dataframe(self):
        global generated_data_global

        self.generated_data = cudf.DataFrame({"HighBP": self.HighBP_nums, 
                                            'HighChol': self.HighChol_nums,
                                            'CholCheck' : self.CholCheck_nums,
                                            'BMI' : self.BMI_nums, 
                                            'Smoker' : self.Smoker_nums, 
                                            'Stroke' : self.Stroke_nums, 
                                            'Diabetes' : self.Diabetes_nums,
                                            'PhysActivity' : self.PhysActivity_nums, 
                                            'Fruits' : self.Fruits_nums, 
                                            'Veggies' : self.Veggies_nums,
                                            'HvyAlcoholConsump' : self.HvyAlcoholConsump_nums, 
                                            'AnyHealthcare' : self.AnyHealthcare_nums, 
                                            'NoDocbcCost' : self.NoDocbcCost_nums,
                                            'GenHlth' : self.GenHlth_nums, 
                                            'MentHlth' : self.MentHlth_nums, 
                                            'PhysHlth' : self.PhysHlth_nums, 
                                            'DiffWalk' : self.DiffWalk_nums, 
                                            'Sex' : self.Sex_nums, 
                                            'Age' : self.Age_nums, 
                                            'Education' : self.Education_nums,
                                            'Income' : self.Income_nums})

        
        generated_data_global = self.generated_data

    def main(self):
        st = time.time()
        self.generating_data()
        self.generating_dataframe()
        et = time.time()
        elapsed_time = et - st
        print('Execution time:', elapsed_time, 'seconds')

In [55]:
torch.cuda.empty_cache()
gc.collect()

1830

In [56]:
gen_df = Data_Generation(df, 253680, float)

In [57]:
gen_df.main()

Execution time: 0.025554180145263672 seconds

In [58]:
generated_data_global_1 = generated_data_global

In [59]:
gen_df_1 = Data_Generation(df, 2000000, float)

In [60]:
gen_df_1.main()

Execution time: 0.04367518424987793 seconds

In [61]:
generated_data_global_2 = generated_data_global

In [62]:
from cuml import LinearRegression
from cuml.linear_model import LinearRegression
from cuml.metrics import mean_squared_error, mean_squared_log_error, median_absolute_error, r2_score, accuracy_score, confusion_matrix, kl_divergence
from cuml.metrics import log_loss, roc_auc_score, nan_euclidean_distances, pairwise_distances, sparse_pairwise_distances
from cuml.model_selection import train_test_split, KFold

In [292]:
class machine_learing(object):
    def __init__(self, dataset, maxAbsScaler_global, MinMaxScaler_global, normalizer_global, robust_scaler_global,
                standard_scaler_global, binarizer_global, function_transformer_global, KBinsDiscretizer_global, generated_data_global_1,
                generated_data_global_2):
        self.dataset = dataset.copy().reset_index(drop = True)
        self.X = cudf.DataFrame(self.dataset.copy().drop(['HeartDiseaseorAttack'], axis = 1))
        self.y = cudf.DataFrame(self.dataset['HeartDiseaseorAttack'].copy())
        self.maxAbsScaler_global = maxAbsScaler_global.copy().reset_index(drop = True)
        self.X_maxAbsScaler_global = cudf.DataFrame(self.maxAbsScaler_global.copy().drop(['HeartDiseaseorAttack'], axis = 1))
        self.y_maxAbsScaler_global = cudf.DataFrame(self.maxAbsScaler_global['HeartDiseaseorAttack'].copy())
        self.MinMaxScaler_global = MinMaxScaler_global.copy().reset_index(drop = True)
        self.X_MinMaxScaler_global = cudf.DataFrame(self.MinMaxScaler_global.copy().drop(['HeartDiseaseorAttack'], axis = 1))
        self.y_MinMaxScaler_global = cudf.DataFrame(self.MinMaxScaler_global['HeartDiseaseorAttack'].copy())
        self.normalizer_global = normalizer_global.copy().reset_index(drop = True)
        self.X_normalizer_global = cudf.DataFrame(self.normalizer_global.copy().drop(['HeartDiseaseorAttack'], axis = 1))
        self.y_normalizer_global = cudf.DataFrame(self.normalizer_global['HeartDiseaseorAttack'].copy())
        self.robust_scaler_global = robust_scaler_global.copy().reset_index(drop = True)
        self.X_robust_scaler_global = cudf.DataFrame(self.robust_scaler_global.copy().drop(['HeartDiseaseorAttack'], axis = 1))
        self.y_robust_scaler_global = cudf.DataFrame(self.robust_scaler_global['HeartDiseaseorAttack'].copy())
        self.standard_scaler_global = standard_scaler_global.copy().reset_index(drop = True)
        self.X_standard_scaler_global = cudf.DataFrame(self.standard_scaler_global.copy().drop(['HeartDiseaseorAttack'], axis = 1))
        self.y_standard_scaler_global = cudf.DataFrame(self.standard_scaler_global['HeartDiseaseorAttack'].copy())
        self.binarizer_global = binarizer_global.copy().reset_index(drop = True)
        self.X_binarizer_global = cudf.DataFrame(self.binarizer_global.copy().drop(['HeartDiseaseorAttack'], axis = 1))
        self.y_binarizer_global = cudf.DataFrame(self.binarizer_global['HeartDiseaseorAttack'].copy())
        self.function_transformer_global = function_transformer_global.copy().reset_index(drop = True)
        self.X_function_transformer_global = cudf.DataFrame(self.function_transformer_global.copy().drop(['HeartDiseaseorAttack'], axis = 1))
        self.y_function_transformer_global = cudf.DataFrame(self.function_transformer_global['HeartDiseaseorAttack'].copy())
        self.KBinsDiscretizer_global = KBinsDiscretizer_global.copy().reset_index(drop = True)
        self.X_KBinsDiscretizer_global = cudf.DataFrame(self.KBinsDiscretizer_global.copy().drop(['HeartDiseaseorAttack'], axis = 1))
        self.y_KBinsDiscretizer_global = cudf.DataFrame(self.KBinsDiscretizer_global['HeartDiseaseorAttack'].copy())
        self.generated_data_global_1 = generated_data_global_1.copy().reset_index(drop = True)
        self.generated_data_global_2 = generated_data_global_2.copy().reset_index(drop = True)

    def train_test_split(self):
        global X_train_global
        global X_test_global
        global y_train_global
        global y_test_global

        X_train, X_test, y_train, y_test = train_test_split(self.X, self.y, test_size=0.2, random_state=42)
        X_train_global = X_train
        X_test_global = X_test
        y_train_global = y_train
        y_test_global = y_test

    def Linear_Regression(self):
        global lr_global
        global lr_predict_test_global
        global lr_predict_global_1
        global lr_predict_global_2
        global mean_squared_error_global_lr
        global mean_squared_log_error_global_lr
        global median_absolute_error_global_lr
        global r2_score_global_lr
        global accuracy_score_global_lr
        global kl_divergence_global_lr
        global log_loss_global_lr
        global roc_auc_score_global_lr
        global nan_euclidean_distances_global_lr
        global pairwise_distances_global_lr
        global sparse_pairwise_distances_global_lr

        model = LinearRegression(fit_intercept = True, algorithm = "eig")
        lr = model.fit(X_train_global.copy(), y_train_global.copy())
        lr_global = lr
        
        preds_test = model.predict(X_test_global.copy())
        lr_predict_test_global = preds_test
        
        mean_squared_error_global_lr = mean_squared_error(y_test_global.copy(), preds_test)
        #mean_squared_log_error_global_lr = mean_squared_log_error(y_test_global.copy(), preds_test)
        median_absolute_error_global_lr = median_absolute_error(y_test_global.copy(), preds_test)
        r2_score_global_lr = r2_score(y_test_global.copy(), preds_test)
        accuracy_score_global_lr = accuracy_score(y_test_global.copy(), preds_test)
        kl_divergence_global_lr = kl_divergence(y_test_global.copy(), preds_test)
        #log_loss_global_lr = log_loss(y_test_global.copy(), preds_test)
        roc_auc_score_global_lr = roc_auc_score(y_test_global.copy(), preds_test)
        #nan_euclidean_distances_global_lr = nan_euclidean_distances(y_test_global.copy(), preds_test)
        #pairwise_distances_global_lr = pairwise_distances(y_test_global.copy(), preds_test)
        #sparse_pairwise_distances_global_lr = sparse_pairwise_distances(y_test_global.copy(), preds_test)
     
        preds_2 = model.predict(self.generated_data_global_2)
        lr_predict_global_2 = cudf.DataFrame(preds_2.copy(), columns = ['HeartDiseaseorAttack']).reset_index(drop = True)

    def LogisticRegression(self):
        
        global logr_global
        global logr_predict_test_global
        global logr_predict_global_1
        global logr_predict_global_2
        global mean_squared_error_global_logr
        global mean_squared_log_error_global_logr
        global median_absolute_error_global_logr
        global r2_score_global_logr
        global accuracy_score_global_logr
        global kl_divergence_global_logr
        global log_loss_global_logr
        global roc_auc_score_global_logr
        global nan_euclidean_distances_global_logr
        global pairwise_distances_global_logr
        global sparse_pairwise_distances_global_logr

        model = cuml.LogisticRegression(penalty='l2', tol=0.0001, C=1.0, fit_intercept=True, class_weight=None, max_iter=1000, 
                                        linesearch_max_iter=50, l1_ratio=None, solver='qn', lbfgs_memory=5, penalty_normalized=True, 
                                        verbose=False, handle=None, output_type=None)
        logr = model.fit(X_train_global.copy(), y_train_global.copy().values.ravel())
        logr_global = logr

        preds_test = model.predict(X_test_global.copy())
        logr_predict_test_global = preds_test
        
        mean_squared_error_global_logr = mean_squared_error(y_test_global.copy(), preds_test)
        mean_squared_log_error_global_logr = mean_squared_log_error(y_test_global.copy(), preds_test)
        median_absolute_error_global_logr = median_absolute_error(y_test_global.copy(), preds_test)
        r2_score_global_logr = r2_score(y_test_global.copy(), preds_test)
        accuracy_score_global_logr = accuracy_score(y_test_global.copy(), preds_test)
        kl_divergence_global_logr = kl_divergence(y_test_global.copy(), preds_test)
        #log_loss_global_logr = log_loss(y_test_global.copy(), preds_test)
        roc_auc_score_global_logr = roc_auc_score(y_test_global.copy(), preds_test)
        #nan_euclidean_distances_global_logr = nan_euclidean_distances(y_test_global.copy(), preds_test)
        #pairwise_distances_global_logr = pairwise_distances(y_test_global.copy(), preds_test)
        #sparse_pairwise_distances_global_logr = sparse_pairwise_distances(y_test_global.copy(), preds_test)
     
        preds_2 = model.predict(self.generated_data_global_2)
        logr_predict_global_2 = cudf.DataFrame(preds_2.copy(), columns = ['HeartDiseaseorAttack']).reset_index(drop = True)

    
    def RidgeRegression(self):
        global ridr_global
        global ridr_predict_test_global
        global ridr_predict_global_1
        global ridr_predict_global_2
        global mean_squared_error_global_ridr
        global mean_squared_log_error_global_ridr
        global median_absolute_error_global_ridr
        global r2_score_global_ridr
        global accuracy_score_global_ridr
        global kl_divergence_global_ridr
        global log_loss_global_ridr
        global roc_auc_score_global_ridr
        global nan_euclidean_distances_global_ridr
        global pairwise_distances_global_ridr
        global sparse_pairwise_distances_global_ridr 

        model = cuml.Ridge(alpha=1e-5, fit_intercept=True, solver='auto', copy_X=True, handle=None, output_type=None, verbose=False)
        ridr = model.fit(X_train_global.copy(), y_train_global.copy().values.ravel())
        ridr_global = ridr

        preds_test = model.predict(X_test_global.copy())
        ridr_predict_test_global = preds_test
        
        mean_squared_error_global_ridr = mean_squared_error(y_test_global.copy(), preds_test)
        #mean_squared_log_error_global_ridr = mean_squared_log_error(y_test_global.copy(), preds_test)
        median_absolute_error_global_ridr = median_absolute_error(y_test_global.copy(), preds_test)
        r2_score_global_ridr = r2_score(y_test_global.copy(), preds_test)
        accuracy_score_global_ridr = accuracy_score(y_test_global.copy(), preds_test)
        kl_divergence_global_ridr = kl_divergence(y_test_global.copy(), preds_test)
        #log_loss_global_ridr = log_loss(y_test_global.copy(), preds_test)
        roc_auc_score_global_ridr = roc_auc_score(y_test_global.copy(), preds_test)
        #nan_euclidean_distances_global_ridr = nan_euclidean_distances(y_test_global.copy(), preds_test)
        #pairwise_distances_global_ridr = pairwise_distances(y_test_global.copy(), preds_test)
        #sparse_pairwise_distances_global_ridr = sparse_pairwise_distances(y_test_global.copy(), preds_test)
     
        preds_2 = model.predict(self.generated_data_global_2)
        ridr_predict_global_2 = cudf.DataFrame(preds_2.copy(), columns = ['HeartDiseaseorAttack']).reset_index(drop = True)

    def LassoRegression(self):
        global lasr_global
        global lasr_predict_test_global
        global lasr_predict_global_1
        global lasr_predict_global_2
        global mean_squared_error_global_lasr
        global mean_squared_log_error_global_lasr
        global median_absolute_error_global_lasr
        global r2_score_global_lasr
        global accuracy_score_global_lasr
        global kl_divergence_global_lasr
        global log_loss_global_lasr
        global roc_auc_score_global_lasr
        global nan_euclidean_distances_global_lasr
        global pairwise_distances_global_lasr
        global sparse_pairwise_distances_global_lasr 

        model = cuml.Lasso(alpha = 0.1, fit_intercept=True, max_iter=1000, tol=0.001, solver='cd', 
                           selection='cyclic', handle=None, output_type=None, verbose=False)
        lasr = model.fit(X_train_global.copy(), y_train_global.copy().values.ravel())
        lasr_global = lasr

        preds_test = model.predict(X_test_global.copy())
        lasr_predict_test_global = preds_test
        
        mean_squared_error_global_lasr = mean_squared_error(y_test_global.copy(), preds_test)
        mean_squared_log_error_global_lasr = mean_squared_log_error(y_test_global.copy(), preds_test)
        median_absolute_error_global_lasr = median_absolute_error(y_test_global.copy(), preds_test)
        r2_score_global_lasr = r2_score(y_test_global.copy(), preds_test)
        accuracy_score_global_lasr = accuracy_score(y_test_global.copy(), preds_test)
        kl_divergence_global_lasr = kl_divergence(y_test_global.copy(), preds_test)
        #log_loss_global_lasr = log_loss(y_test_global.copy(), preds_test)
        roc_auc_score_global_lasr = roc_auc_score(y_test_global.copy(), preds_test)
        #nan_euclidean_distances_global_lasr = nan_euclidean_distances(y_test_global.copy(), preds_test)
        #pairwise_distances_global_lasr = pairwise_distances(y_test_global.copy(), preds_test)
        #sparse_pairwise_distances_global_lasr = sparse_pairwise_distances(y_test_global.copy(), preds_test)
     
        preds_2 = model.predict(self.generated_data_global_2)
        lasr_predict_global_2 = cudf.DataFrame(preds_2.copy(), columns = ['HeartDiseaseorAttack']).reset_index(drop = True)

    def ElasticNetRegression(self):
        global enr_global
        global enr_predict_test_global
        global enr_predict_global_1
        global enr_predict_global_2
        global mean_squared_error_global_enr
        global mean_squared_log_error_global_enr
        global median_absolute_error_global_enr
        global r2_score_global_enr
        global accuracy_score_global_enr
        global kl_divergence_global_enr
        global log_loss_global_enr
        global roc_auc_score_global_enr
        global nan_euclidean_distances_global_enr
        global pairwise_distances_global_enr
        global sparse_pairwise_distances_global_enr 

        model = cuml.ElasticNet(alpha = 0.1, l1_ratio=0.5, fit_intercept=True, max_iter=1000, tol=0.001, solver='cd', selection='cyclic', 
                                handle=None, output_type=None, verbose=False)
        enr = model.fit(X_train_global.copy(), y_train_global.copy().values.ravel())
        enr_global = enr

        preds_test = model.predict(X_test_global.copy())
        enr_predict_test_global = preds_test
        
        mean_squared_error_global_enr = mean_squared_error(y_test_global.copy(), preds_test)
        #mean_squared_log_error_global_enr = mean_squared_log_error(y_test_global.copy(), preds_test)
        median_absolute_error_global_enr = median_absolute_error(y_test_global.copy(), preds_test)
        r2_score_global_enr = r2_score(y_test_global.copy(), preds_test)
        accuracy_score_global_enr = accuracy_score(y_test_global.copy(), preds_test)
        kl_divergence_global_enr = kl_divergence(y_test_global.copy(), preds_test)
        #log_loss_global_enr = log_loss(y_test_global.copy(), preds_test)
        roc_auc_score_global_enr = roc_auc_score(y_test_global.copy(), preds_test)
        #nan_euclidean_distances_global_enr = nan_euclidean_distances(y_test_global.copy(), preds_test)
        #pairwise_distances_global_enr = pairwise_distances(y_test_global.copy(), preds_test)
        #sparse_pairwise_distances_global_enr = sparse_pairwise_distances(y_test_global.copy(), preds_test)
     
        preds_2 = model.predict(self.generated_data_global_2)
        enr_predict_global_2 = cudf.DataFrame(preds_2.copy(), columns = ['HeartDiseaseorAttack']).reset_index(drop = True)

    def MiniBatchSGDClassifier(self):
        global mbc_global
        global mbc_predict_test_global
        global mbc_predict_global_1
        global mbc_predict_global_2
        global mean_squared_error_global_mbc
        global mean_squared_log_error_global_mbc
        global median_absolute_error_global_mbc
        global r2_score_global_mbc
        global accuracy_score_global_mbc
        global kl_divergence_global_mbc
        global log_loss_global_mbc
        global roc_auc_score_global_mbc
        global nan_euclidean_distances_global_mbc
        global pairwise_distances_global_mbc
        global sparse_pairwise_distances_global_mbc 

        model = cuml.MBSGDClassifier(loss='hinge', penalty='l2', alpha=0.0001, l1_ratio=0.15, fit_intercept=True, epochs=1000, tol=0.001, 
                                     shuffle=True, learning_rate='constant', eta0=0.001, power_t=0.5, batch_size=32, n_iter_no_change=5, 
                                     handle=None, verbose=False, output_type=None)
        mbc = model.fit(X_train_global.copy(), y_train_global.copy().values.ravel())
        mbc_global = mbc

        preds_test = model.predict(X_test_global.copy())
        mbc_predict_test_global = preds_test
        
        mean_squared_error_global_mbc = mean_squared_error(y_test_global.copy(), preds_test)
        #mean_squared_log_error_global_mbc = mean_squared_log_error(y_test_global.copy(), preds_test)
        median_absolute_error_global_mbc = median_absolute_error(y_test_global.copy(), preds_test)
        r2_score_global_mbc = r2_score(y_test_global.copy(), preds_test)
        accuracy_score_global_mbc = accuracy_score(y_test_global.copy(), preds_test)
        kl_divergence_global_mbc = kl_divergence(y_test_global.copy(), preds_test)
        #log_loss_global_mbc = log_loss(y_test_global.copy(), preds_test)
        roc_auc_score_global_mbc = roc_auc_score(y_test_global.copy(), preds_test)
        #nan_euclidean_distances_global_mbc = nan_euclidean_distances(y_test_global.copy(), preds_test)
        #pairwise_distances_global_mbc = pairwise_distances(y_test_global.copy(), preds_test)
        #sparse_pairwise_distances_global_mbc = sparse_pairwise_distances(y_test_global.copy(), preds_test)
     
        preds_2 = model.predict(self.generated_data_global_2)
        mbc_predict_global_2 = cudf.DataFrame(preds_2.copy(), columns = ['HeartDiseaseorAttack']).reset_index(drop = True)
        
    def main(self):
        st = time.time()
        self.train_test_split()
        self.Linear_Regression()
        self.LogisticRegression()
        self.RidgeRegression()
        self.LassoRegression()
        self.ElasticNetRegression()
        self.MiniBatchSGDClassifier()
        et = time.time()
        elapsed_time = et - st
        print('Execution time:', elapsed_time, 'seconds')

In [293]:
ml = machine_learing(df, maxAbsScaler_global, MinMaxScaler_global, normalizer_global, robust_scaler_global,
                standard_scaler_global, binarizer_global, function_transformer_global, KBinsDiscretizer_global, generated_data_global_1, 
                    generated_data_global_2)

In [294]:
torch.cuda.empty_cache()
gc.collect()

41

In [295]:
ml.main()

Execution time: 316.6909132003784 seconds

In [296]:
lr_global

LinearRegression()

In [297]:
logr_global

LogisticRegression()

In [298]:
ridr_global

Ridge(alpha=1e-05)

In [299]:
lasr_global

Lasso(alpha=0.1)

In [300]:
enr_global

ElasticNet(alpha=0.1)

In [301]:
mbc_global

MBSGDClassifier()

In [302]:
class MetricsLinearRegression(object):
    def LinearRegression(self):
        print(' Linear Regression Coef: ')
        print(lr_global.coef_)
        print('\n')
        print('Linear Regression Intercept: ')
        print(lr_global.intercept_)
        print('\n')
        print('Mean squared error: ')
        print(mean_squared_error_global_lr)
        print('\n')
        print('Median Absolute Error: ')
        print(median_absolute_error_global_lr)
        print('\n')
        print('R2 Score: ')
        print(r2_score_global_lr)
        print('\n')
        print('Accuracy Score: ')
        print(accuracy_score_global_lr)
        print('\n')
        print('Kl Divergence: ')
        print(kl_divergence_global_lr)
        print('\n')
        print('ROC AUC Score: ')
        print(roc_auc_score_global_lr)
        print('\n')
        print('Unique Values:')
        print(lr_predict_test_global.unique())
        
    def main(self):
        self.LinearRegression()

In [303]:
metrics_lr = MetricsLinearRegression()
metrics_lr.main()

 Linear Regression Coef:
0     0.034075
1     0.038439
2     0.013089
3    -0.001243
4     0.023097
5     0.188192
6     0.024651
7     0.004049
8     0.003699
9     0.003634
10   -0.020996
11    0.006711
12    0.007132
13    0.032995
14   -0.000172
15    0.000954
16    0.049416
17    0.052903
18    0.010917
19    0.001196
20   -0.003696
dtype: float64


Linear Regression Intercept:
-0.14270589939938821


Mean squared error:
0.07244965790139617


Median Absolute Error:
0.08481782247394984


R2 Score:
0.14910311630139816


Accuracy Score:
0.0


Kl Divergence:
nan


ROC AUC Score:
0.839693546295166


Unique Values:
0        0.037284
1        0.152095
2       -0.065624
3       -0.027555
4        0.200609
           ...
48601    0.063997
48602    0.146988
48603    0.018342
48604    0.086597
48605    0.194234
Length: 48606, dtype: float64

In [304]:
class MetricsLogisticRegression(object):
    def LogisticRegression(self):
        print(' Logistic Regression Coef: ')
        print(logr_global.coef_)
        print('\n')
        print('Logistic Regression Intercept: ')
        print(logr_global.intercept_)
        print('\n')
        print('Mean squared error: ')
        print(mean_squared_error_global_logr)
        print('\n')
        print('Mean Squared Log Error: ')
        print(mean_squared_log_error_global_logr)
        print('\n')
        print('Median Absolute Error: ')
        print(median_absolute_error_global_logr)
        print('\n')
        print('R2 Score: ')
        print(r2_score_global_logr)
        print('\n')
        print('Accuracy Score: ')
        print(accuracy_score_global_logr)
        print('\n')
        print('Kl Divergence: ')
        print(kl_divergence_global_logr)
        print('\n')
        print('ROC AUC Score: ')
        print(roc_auc_score_global_logr)
        print('\n')
        print('Unique Values:')
        print(logr_predict_test_global.unique())
        
    def main(self):
        self.LogisticRegression()

In [305]:
metrics_logr = MetricsLogisticRegression()
metrics_logr.main()

 Logistic Regression Coef:
         0         1         2         3         4         5         6   \
0  0.526517  0.604099  0.436289  0.000577  0.363925  0.996358  0.154293

         7         8        9   ...        11        12        13        14  \
0  0.045981  0.002891  0.04318  ... -0.042344  0.241117  0.491667  0.002245

         15        16        17        18        19        20
0  0.001156  0.285292  0.756221  0.252019  0.012735 -0.045056

[1 rows x 21 columns]


Logistic Regression Intercept:
0   -7.740664
dtype: float64


Mean squared error:
0.09163118889940082


Mean Squared Log Error:
0.04402448087562516


Median Absolute Error:
0.0


R2 Score:
-0.07617751888094904


Accuracy Score:
0.9083688111005992


Kl Divergence:
inf


ROC AUC Score:
0.5601312518119812


Unique Values:
0    0.0
1    1.0
dtype: float64

In [306]:
class MetricsRidgeRegression(object):
    def RidgeRegression(self):
        print('Ridge Regression Coef: ')
        print(ridr_global.coef_)
        print('\n')
        print('Ridge Regression Intercept: ')
        print(ridr_global.intercept_)
        print('\n')
        print('Mean squared error: ')
        print(mean_squared_error_global_ridr)
        print('\n')
        print('Median Absolute Error: ')
        print(median_absolute_error_global_ridr)
        print('\n')
        print('R2 Score: ')
        print(r2_score_global_ridr)
        print('\n')
        print('Accuracy Score: ')
        print(accuracy_score_global_ridr)
        print('\n')
        print('Kl Divergence: ')
        print(kl_divergence_global_ridr)
        print('\n')
        print('ROC AUC Score: ')
        print(roc_auc_score_global_ridr)
        print('\n')
        print('Unique Values:')
        print(ridr_predict_test_global.unique())
        
    def main(self):
        self.RidgeRegression()

In [307]:
metrics_ridr = MetricsRidgeRegression()
metrics_ridr.main()

Ridge Regression Coef:
0     0.034075
1     0.038439
2     0.013089
3    -0.001243
4     0.023097
5     0.188192
6     0.024651
7     0.004049
8     0.003699
9     0.003634
10   -0.020996
11    0.006711
12    0.007132
13    0.032995
14   -0.000172
15    0.000954
16    0.049416
17    0.052903
18    0.010917
19    0.001196
20   -0.003696
dtype: float64


Ridge Regression Intercept:
-0.14270589937698436


Mean squared error:
0.07244965790136305


Median Absolute Error:
0.08481782247862378


R2 Score:
0.14910311630178708


Accuracy Score:
0.0


Kl Divergence:
nan


ROC AUC Score:
0.839693546295166


Unique Values:
0        0.037284
1        0.152095
2       -0.065624
3       -0.027555
4        0.200609
           ...
48601    0.063997
48602    0.146988
48603    0.018342
48604    0.086597
48605    0.194234
Length: 48606, dtype: float64

In [308]:
class MetricsLassoRegression(object):
    def LassoRegression(self):
        print(' Lasso Regression Coef: ')
        print(lasr_global.coef_)
        print('\n')
        print('Lasso Regression Intercept: ')
        print(lasr_global.intercept_)
        print('\n')
        print('Mean squared error: ')
        print(mean_squared_error_global_lasr)
        print('\n')
        print('Mean Squared Log Error: ')
        print(mean_squared_log_error_global_lasr)
        print('\n')
        print('Median Absolute Error: ')
        print(median_absolute_error_global_lasr)
        print('\n')
        print('R2 Score: ')
        print(r2_score_global_lasr)
        print('\n')
        print('Accuracy Score: ')
        print(accuracy_score_global_lasr)
        print('\n')
        print('Kl Divergence: ')
        print(kl_divergence_global_lasr)
        print('\n')
        print('ROC AUC Score: ')
        print(roc_auc_score_global_lasr)
        print('\n')
        print('Unique Values:')
        print(lasr_predict_test_global.unique())
        
    def main(self):
        self.LassoRegression()

In [309]:
metrics_lasr = MetricsLassoRegression()
metrics_lasr.main()

 Lasso Regression Coef:
0     0.000000
1     0.000000
2     0.000000
3     0.000000
4     0.000000
5     0.000000
6     0.000000
7     0.000000
8     0.000000
9     0.000000
10    0.000000
11    0.000000
12    0.000000
13    0.000000
14    0.000000
15    0.004458
16    0.000000
17    0.000000
18    0.009080
19    0.000000
20    0.000000
dtype: float64


Lasso Regression Intercept:
0.002353189228692043


Mean squared error:
0.07984105108357516


Mean Squared Log Error:
0.03863018127579227


Median Absolute Error:
0.0880449164019414


R2 Score:
0.062293687422286914


Accuracy Score:
0.0


Kl Divergence:
9917.789239056243


ROC AUC Score:
0.7625166177749634


Unique Values:
0      0.097125
1      0.120399
2      0.011434
3      0.020514
4      0.195374
         ...
336    0.145514
337    0.109519
338    0.145350
339    0.114959
340    0.159707
Length: 341, dtype: float64

In [336]:
class MetricsElasticNetRegression(object):
    def ElasticNetRegression(self):
        print('ElasticNet Regression Coef: ')
        print(enr_global.coef_)
        print('\n')
        print('ElasticNet Regression Intercept: ')
        print(enr_global.intercept_)
        print('\n')
        print('Mean squared error: ')
        print(mean_squared_error_global_enr)
        print('\n')
        print('Median Absolute Error: ')
        print(median_absolute_error_global_enr)
        print('\n')
        print('R2 Score: ')
        print(r2_score_global_enr)
        print('\n')
        print('Accuracy Score: ')
        print(accuracy_score_global_enr)
        print('\n')
        print('Kl Divergence: ')
        print(kl_divergence_global_enr)
        print('\n')
        print('ROC AUC Score: ')
        print(roc_auc_score_global_enr)
        print('\n')
        print('Unique Values:')
        print(enr_predict_test_global.unique())
        
    def main(self):
        self.ElasticNetRegression()

In [337]:
metrics_enr = MetricsElasticNetRegression()
metrics_enr.main()

ElasticNet Regression Coef:
0     0.000000
1     0.000000
2     0.000000
3     0.000684
4     0.000000
5     0.000000
6     0.000000
7     0.000000
8     0.000000
9     0.000000
10    0.000000
11    0.000000
12    0.000000
13    0.000000
14    0.000159
15    0.004819
16    0.000000
17    0.000000
18    0.014354
19    0.000000
20    0.000000
dtype: float64


ElasticNet Regression Intercept:
-0.06144692471100964


Mean squared error:
0.07883600554579503


Median Absolute Error:
0.09046160208527505


R2 Score:
0.074097609495131


Accuracy Score:
0.0


Kl Divergence:
nan


ROC AUC Score:
0.7695364952087402


Unique Values:
0        0.087599
1        0.144298
2       -0.030681
3       -0.013799
4        0.208987
           ...
13238    0.110986
13239    0.037549
13240    0.042662
13241    0.097118
13242    0.147535
Length: 13243, dtype: float64

In [328]:
class MetricsMiniBatchSGDClassifier(object):
    def MiniBatchSGDClassifier(self):
        print('Mini Batch SGD Classifier Coef: ')
        print(mbc_global.coef_)
        print('\n')
        print('Mini Batch SGD Classifier Intercept: ')
        print(mbc_global.intercept_)
        print('\n')
        print('Mean squared error: ')
        print(mean_squared_error_global_mbc)
        print('\n')
        print('Median Absolute Error: ')
        print(median_absolute_error_global_mbc)
        print('\n')
        print('R2 Score: ')
        print(r2_score_global_mbc)
        print('\n')
        print('Accuracy Score: ')
        print(accuracy_score_global_mbc)
        print('\n')
        print('Kl Divergence: ')
        print(kl_divergence_global_mbc)
        print('\n')
        print('ROC AUC Score: ')
        print(roc_auc_score_global_mbc)
        print('\n')
        print('Unique Values:')
        print(mbc_predict_test_global.unique())
        
    def main(self):
        self.MiniBatchSGDClassifier()

In [329]:
metrics_mbc = MetricsMiniBatchSGDClassifier()
metrics_mbc.main()

Mini Batch SGD Classifier Coef:
0     2.309240
1     2.232210
2     0.699239
3    -0.039579
4     1.126629
5     3.218573
6     1.376952
7     0.131409
8     0.064174
9     0.105607
10   -0.464631
11    0.006140
12    0.553335
13    1.770691
14    0.023755
15    0.157523
16    1.838907
17    2.560925
18    0.960408
19   -0.080371
20   -0.386138
dtype: float64


Mini Batch SGD Classifier Intercept:
-14.283955410503758


Mean squared error:
0.394138284452854


Median Absolute Error:
0.0


R2 Score:
-3.629021691775078


Accuracy Score:
0.605861715547146


Kl Divergence:
inf


ROC AUC Score:
0.7450825572013855


Unique Values:
0    0.0
1    1.0
dtype: float64

In [330]:
lr_predict_global_2

         HeartDiseaseorAttack
0                    0.157884
1                    0.124386
2                    0.194886
3                    0.292296
4                    0.005990
...                       ...
1999995              0.193246
1999996              0.119913
1999997             -0.039328
1999998             -0.004768
1999999              0.153136

[2000000 rows x 1 columns]

In [331]:
logr_predict_global_2

         HeartDiseaseorAttack
0                         0.0
1                         0.0
2                         0.0
3                         0.0
4                         0.0
...                       ...
1999995                   0.0
1999996                   0.0
1999997                   0.0
1999998                   0.0
1999999                   0.0

[2000000 rows x 1 columns]

In [332]:
ridr_predict_global_2

         HeartDiseaseorAttack
0                    0.157884
1                    0.124386
2                    0.194886
3                    0.292296
4                    0.005990
...                       ...
1999995              0.193246
1999996              0.119913
1999997             -0.039328
1999998             -0.004768
1999999              0.153136

[2000000 rows x 1 columns]

In [333]:
lasr_predict_global_2

         HeartDiseaseorAttack
0                    0.167969
1                    0.133284
2                    0.047592
3                    0.096307
4                    0.109519
...                       ...
1999995              0.155903
1999996              0.078964
1999997              0.061294
1999998              0.115286
1999999              0.024973

[2000000 rows x 1 columns]

In [334]:
enr_predict_global_2

         HeartDiseaseorAttack
0                    0.167828
1                    0.175700
2                    0.031097
3                    0.060713
4                    0.113125
...                       ...
1999995              0.197885
1999996              0.080791
1999997              0.073690
1999998              0.159087
1999999              0.040813

[2000000 rows x 1 columns]

In [335]:
mbc_predict_global_2

         HeartDiseaseorAttack
0                         0.0
1                         1.0
2                         0.0
3                         1.0
4                         0.0
...                       ...
1999995                   1.0
1999996                   1.0
1999997                   0.0
1999998                   0.0
1999999                   0.0

[2000000 rows x 1 columns]